# Uncomment the next line to define a global platform for your project
platform :ios, '7.0'

target 'NendSDK_AdMobMediationSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  pod 'Google-Mobile-Ads-SDK'
  pod 'NendSDK_iOS'
  pod 'NendSDK_iOS_MediationAdapter'

end
